#NEW
"https://soundcloud.com/octobersveryown/drake-draft-day"
"https://soundcloud.com/octobersveryown/drake-0-to-100"
"https://soundcloud.com/ob-obrien/ob-obrien-2-onthotful-feat-drake"
"https://soundcloud.com/partyomo/partynextdoor-recognize-feat-drake"
"https://soundcloud.com/octobersveryown/drake-trophies"
#MID
"https://soundcloud.com/octobersveryown/drake-hold-on-were-going-home"
"https://soundcloud.com/octobersveryown/drake-5am-in-toronto"
"https://soundcloud.com/octobersveryown/drake-the-motto-feat-lil-wayne"
"https://soundcloud.com/octobersveryown/drake-started-from-the-bottom"
"https://soundcloud.com/octobersveryown/lil-wayne-she-will-feat-drake"